# Generated by Django 6.0.3 on 2026-03-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00')], unique=True, verbose_name='Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('primary_care', 'Medicina general'), ('cardiology', 'Cardiología'), ('pediatrics', 'Pediatría'), ('surgery', 'Cirugía'), ('dermatology', 'Dermatología'), ('obgyn', 'Obstetriciaginecología'), ('ent', 'Otorrinonaringología'), ('ge', 'Gastroenterología')], unique=True, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.person')),
            ],
            bases=('schedule.person',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.person')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.specialty', verbose_name='Especialidad')),
            ],
            bases=('schedule.person',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time', to='schedule.availability', verbose_name='Hora')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reason', to='schedule.specialty', verbose_name='Motivo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='schedule.patient', verbose_name='Paciente')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='schedule.provider', verbose_name='Especialista')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'provider', 'time'), name='unique_appointment')],
            },
        ),
    ]
